POST http://localhost:8000/ecd/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="hea"; filename="JS00005.hea"

< ../ecd_sandbox/files/JS00005.hea

--boundary
Content-Disposition: form-data; name="mat"; filename="JS00005.mat"

< ../ecd_sandbox/files/JS00005.mat
--boundary

###

GET http://879f9f33fd0d.ngrok.app/ecd/allFiles

###

GET http://localhost:8000/ecd/signal?ecd_id=661e482f456229e631b7a6d2&signal_type=I

###

GET http://localhost:8000/ecd/size
