POST http://localhost:8000/ecd/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="hea"; filename="JS35102.hea"

< ../ecd_sandbox/files/JS35102.hea

--boundary
Content-Disposition: form-data; name="mat"; filename="JS35102.mat"

< ../ecd_sandbox/files/JS35102.mat
--boundary

###

GET http://localhost:8000/ecd/allFiles

###

GET http://localhost:8000/ecd/signal?ecd_id=661d1c62f8412ab9eedda67c&signal_type=I
