POST http://localhost:8000/ecd/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="hea"; filename="JS00005.hea"

< ../ecd_sandbox/files/JS00005.hea

--boundary
Content-Disposition: form-data; name="mat"; filename="JS00005.mat"

< ../ecd_sandbox/files/JS00005.mat
--boundary

###

GET http://localhost:8000/ecd/allFiles

###

GET http://localhost:8000/ecd/signal?ecd_id=661e482f456229e631b7a6d2&signal_type=I

###

GET http://localhost:8000/ecd/analyze?ecd_id=663bae7255f3f45305380126

###

POST localhost:8000/ecd/addP
Content-Type: application/json

{
  "ecd_id": "665f010c7d086740eb00e501",
  "signal": "I",
  "index": 1000
}
