version: '3.7'

services:
  pz-fastapi:
    build: ../backend
    ports:
      - 8000:8000
    networks:
      - backend

  pz-front:
    build: ../frontend
    ports:
      - 3000:3000
    networks:
      - backend

  pz-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGODB_INITDB_DATABASE: ecdHelperDB
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
